/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dobackaofront.lanchonete.view;

import br.com.dobackaofront.lanchonete.model.Lanche;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Família Santos
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrameCadastroLanche = new javax.swing.JInternalFrame();
        jLabelCadastroLancheNome = new javax.swing.JLabel();
        jTextFieldCadastroLancheNome = new javax.swing.JTextField();
        jLabelCadastroLanchePreco = new javax.swing.JLabel();
        jTextFieldCadastroLanchePreco = new javax.swing.JTextField();
        jButtonCadastroLancheSalvar = new javax.swing.JButton();
        jButtonCadastroLancheCancelar = new javax.swing.JButton();
        jInternalFramePesquisar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPorNome = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesquisarAcao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPesquisarID = new javax.swing.JTextField();
        jButtonPesquisarConfirmar = new javax.swing.JButton();
        jButtonPesquisarCancelar = new javax.swing.JButton();
        jLabelPesquisarQuantidade = new javax.swing.JLabel();
        jTextFieldPesquisarQuantidade = new javax.swing.JTextField();
        jInternalFrameEditarCadastro = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditarPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditarId = new javax.swing.JTextField();
        jButtonEditarSalvar = new javax.swing.JButton();
        jButtonEditarCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroLanche = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdicaoLanche = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarLanche = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendasCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanchonete Do Back ao Front");

        jInternalFrameCadastroLanche.setTitle("Cadastro de Lanche");
        jInternalFrameCadastroLanche.setVisible(false);

        jLabelCadastroLancheNome.setText("Nome do Lanche:");

        jLabelCadastroLanchePreco.setText("Preço:");

        jButtonCadastroLancheSalvar.setText("Salvar");
        jButtonCadastroLancheSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroLancheCancelar.setText("Cancelar");
        jButtonCadastroLancheCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroLancheLayout = new javax.swing.GroupLayout(jInternalFrameCadastroLanche.getContentPane());
        jInternalFrameCadastroLanche.getContentPane().setLayout(jInternalFrameCadastroLancheLayout);
        jInternalFrameCadastroLancheLayout.setHorizontalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroLancheSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroLancheCancelar))
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadastroLancheNome)
                            .addComponent(jLabelCadastroLanchePreco))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameCadastroLancheLayout.setVerticalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroLancheNome))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLanchePreco)
                    .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroLancheSalvar)
                    .addComponent(jButtonCadastroLancheCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFramePesquisar.setTitle("Pesquisar pelo Nome");
        jInternalFramePesquisar.setVisible(true);

        jTablePesquisarPorNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarPorNome);

        jLabel1.setText("Selecione a ação Desejada:");

        jComboBoxPesquisarAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Excluir", "Adicionar no Carrinho" }));

        jLabel2.setText("Qual o ID do lanche:");

        jButtonPesquisarConfirmar.setText("Confirmar");
        jButtonPesquisarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarConfirmarActionPerformed(evt);
            }
        });

        jButtonPesquisarCancelar.setText("Cancelar");
        jButtonPesquisarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCancelarActionPerformed(evt);
            }
        });

        jLabelPesquisarQuantidade.setText("Quantidade:");

        javax.swing.GroupLayout jInternalFramePesquisarLayout = new javax.swing.GroupLayout(jInternalFramePesquisar.getContentPane());
        jInternalFramePesquisar.getContentPane().setLayout(jInternalFramePesquisarLayout);
        jInternalFramePesquisarLayout.setHorizontalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarConfirmar)
                        .addGap(18, 18, 18))
                    .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabelPesquisarQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPesquisarAcao, 0, 142, Short.MAX_VALUE)
                            .addComponent(jTextFieldPesquisarID)
                            .addComponent(jTextFieldPesquisarQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonPesquisarCancelar)
                .addContainerGap())
        );
        jInternalFramePesquisarLayout.setVerticalGroup(
            jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPesquisarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisarQuantidade)
                    .addComponent(jTextFieldPesquisarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarConfirmar)
                    .addComponent(jButtonPesquisarCancelar))
                .addContainerGap())
        );

        jInternalFrameEditarCadastro.setTitle("Edição de Cadastro");
        jInternalFrameEditarCadastro.setVisible(true);

        jLabel3.setText("Nome do Lanche:");

        jLabel4.setText("Preço:");

        jLabel5.setText("ID:");

        jTextFieldEditarId.setEnabled(false);

        jButtonEditarSalvar.setText("Salvar");
        jButtonEditarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvarActionPerformed(evt);
            }
        });

        jButtonEditarCancelar.setText("Cancelar");
        jButtonEditarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameEditarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameEditarCadastro.getContentPane());
        jInternalFrameEditarCadastro.getContentPane().setLayout(jInternalFrameEditarCadastroLayout);
        jInternalFrameEditarCadastroLayout.setHorizontalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                            .addComponent(jButtonEditarSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditarCancelar))
                        .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEditarNome)
                            .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jInternalFrameEditarCadastroLayout.setVerticalGroup(
            jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jInternalFrameEditarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarSalvar)
                    .addComponent(jButtonEditarCancelar))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jDesktopPane.setLayer(jInternalFrameCadastroLanche, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jInternalFramePesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jInternalFrameEditarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneLayout.createSequentialGroup()
                    .addGap(321, 321, 321)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrameCadastroLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneLayout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jInternalFrameEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroLanche.setText("Lanche");
        jMenuItemCadastroLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroLancheActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroLanche);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdicaoLanche.setText("Lanche");
        jMenuItemEdicaoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdicaoLancheActionPerformed(evt);
            }
        });
        jMenuEdicao.add(jMenuItemEdicaoLanche);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarLanche.setText("Lanche");
        jMenuItemPesquisarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarLancheActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesquisarLanche);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendasCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendasCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroLancheActionPerformed
        jInternalFrameCadastroLanche.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroLancheActionPerformed

    private void jButtonCadastroLancheCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroLancheNome.setText("");
        jTextFieldCadastroLanchePreco.setText("");
        jInternalFrameCadastroLanche.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroLancheCancelarActionPerformed

    private void jButtonCadastroLancheSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldCadastroLancheNome.getText();
        
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome do Lanche está vazio!");
        } else {
            String preco = jTextFieldCadastroLanchePreco.getText();
            
            if (preco.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "O campo Preço está vazio!");
            } else {
                try {
                    double precoConvertido = Double.parseDouble(preco);
                    Lanche lanche = new Lanche(nome, precoConvertido);
                    lanche.apresentarLanche();
                    lanche.salvar(nome, precoConvertido);
                    
                    jTextFieldCadastroLancheNome.setText("");
                    jTextFieldCadastroLanchePreco.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane, "O Lanche "+nome+" foi cadastro com Sucesso!");
                    
                    jInternalFrameCadastroLanche.setVisible(false);
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Preencha o preço do lanche apenas com números separados por ponto ao invés de vírgula!");
                }
            }
        }
        
        
    }//GEN-LAST:event_jButtonCadastroLancheSalvarActionPerformed

    private void jMenuItemPesquisarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarLancheActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Informe o Nome: ");
        Lanche lanche = new Lanche();
        ArrayList<Lanche> lanches = lanche.pesquisar(nome);
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");
        
        for (Lanche lancheAux : lanches) {
            modelo.addRow(new Object[]{lancheAux.getId(), lancheAux.getNome(), lancheAux.getPreco()});
            jTablePesquisarPorNome.setModel(modelo);
        }
        
        jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarLancheActionPerformed

    private void jButtonPesquisarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarConfirmarActionPerformed
        // TODO add your handling code here:
        Lanche lanche = new Lanche();
        String opcao = jComboBoxPesquisarAcao.getSelectedItem().toString();
        System.out.println("Opção selecionada: "+opcao);
        
        int idPesquisar = Integer.parseInt(jTextFieldPesquisarID.getText());
        System.out.println("ID Informado: "+idPesquisar);
        if (opcao.equals("Excluir")) {
            lanche.deletar(idPesquisar);
            JOptionPane.showMessageDialog(rootPane, "O Lanche de ID: "+idPesquisar+" foi excluido com Sucesso!");
            
            jComboBoxPesquisarAcao.setSelectedIndex(0);
            jTextFieldPesquisarID.setText("");
            jInternalFramePesquisar.setVisible(false);
        } else if (opcao.equals("Editar")){ // editar
            jInternalFramePesquisar.setVisible(false);
            
            Lanche lancheRecuperado = lanche.bucarPorId(idPesquisar);
            
            jTextFieldEditarId.setText(idPesquisar+"");
            jTextFieldEditarNome.setText(lancheRecuperado.getNome());
            jTextFieldEditarPreco.setText(lancheRecuperado.getPreco()+"");
            jInternalFrameEditarCadastro.setVisible(true);
        } else if (opcao.equals("Adicionar no Carrinho")){ // adicionar no carrinho
            JOptionPane.showMessageDialog(rootPane, "O lanche foi adicicionado no carrinho!");
            jTextFieldPesquisarID.setText("");
            jComboBoxPesquisarAcao.setSelectedIndex(0);
            jInternalFramePesquisar.setVisible(false);
        }
    }//GEN-LAST:event_jButtonPesquisarConfirmarActionPerformed

    private void jButtonPesquisarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisarID.setText("");
        jComboBoxPesquisarAcao.setSelectedIndex(0);
        jInternalFramePesquisar.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCancelarActionPerformed

    private void jButtonEditarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldEditarNome.getText();
        double preco = Double.parseDouble(jTextFieldEditarPreco.getText());
        int id = Integer.parseInt(jTextFieldEditarId.getText());
        
        Lanche lanche = new Lanche();
        lanche.editar(nome, preco, id);
        
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        JOptionPane.showMessageDialog(rootPane, "O Lanche foi Atualizado com Sucesso!");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarSalvarActionPerformed

    private void jButtonEditarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldEditarId.setText("");
        jTextFieldEditarNome.setText("");
        jTextFieldEditarPreco.setText("");
        
        jInternalFrameEditarCadastro.setVisible(false);
    }//GEN-LAST:event_jButtonEditarCancelarActionPerformed

    private void jMenuItemEdicaoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdicaoLancheActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Informe o Nome: ");
        Lanche lanche = new Lanche();
        ArrayList<Lanche> lanches = lanche.pesquisar(nome);
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Preço");
        
        for (Lanche lancheAux : lanches) {
            modelo.addRow(new Object[]{lancheAux.getId(), lancheAux.getNome(), lancheAux.getPreco()});
            jTablePesquisarPorNome.setModel(modelo);
        }
        
        jInternalFramePesquisar.setVisible(true);
    }//GEN-LAST:event_jMenuItemEdicaoLancheActionPerformed

    
    public JInternalFrame getJInternalFrameEditarCadastro() {
        return jInternalFrameEditarCadastro;
    }
    /**
     * @param args the command line arguments
     */
    public JInternalFrame getJInternalFrameCadastroLanche() {
        return jInternalFrameCadastroLanche;
    }
    
    public JInternalFrame getJInternalFramePesquisar() {
        return jInternalFramePesquisar;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroLancheCancelar;
    private javax.swing.JButton jButtonCadastroLancheSalvar;
    private javax.swing.JButton jButtonEditarCancelar;
    private javax.swing.JButton jButtonEditarSalvar;
    private javax.swing.JButton jButtonPesquisarCancelar;
    private javax.swing.JButton jButtonPesquisarConfirmar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarAcao;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jInternalFrameCadastroLanche;
    private javax.swing.JInternalFrame jInternalFrameEditarCadastro;
    private javax.swing.JInternalFrame jInternalFramePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastroLancheNome;
    private javax.swing.JLabel jLabelCadastroLanchePreco;
    private javax.swing.JLabel jLabelPesquisarQuantidade;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroLanche;
    private javax.swing.JMenuItem jMenuItemEdicaoLanche;
    private javax.swing.JMenuItem jMenuItemPesquisarLanche;
    private javax.swing.JMenuItem jMenuItemVendasCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisarPorNome;
    private javax.swing.JTextField jTextFieldCadastroLancheNome;
    private javax.swing.JTextField jTextFieldCadastroLanchePreco;
    private javax.swing.JTextField jTextFieldEditarId;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarPreco;
    private javax.swing.JTextField jTextFieldPesquisarID;
    private javax.swing.JTextField jTextFieldPesquisarQuantidade;
    // End of variables declaration//GEN-END:variables
}
